[package]
name = "atticus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
thiserror = "1.0.40"
tokio = { version = "1.20", features = ["rt", "test-util", "tokio-macros", "macros"] }
